version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: pulseq_postgres
    environment:
      POSTGRES_USER: pulseq_admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: pulseq_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7-alpine
    container_name: job_queue_redis
    ports:
      - "6379:6379"
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: job_queue_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: job_queue_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus
    restart: always

  minio:
    image: minio/minio
    container_name: job_queue_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    restart: always

  createbuckets:
    image: minio/mc
    container_name: job_queue_createbuckets
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c " sleep 5; /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin; /usr/bin/mc mb myminio/pulseq; /usr/bin/mc anonymous set public myminio/pulseq; exit 0; "

volumes:
  postgres_data:
  minio_data:
